# FreeForAll By Harry5573
# Configuration
enabled: true
teleportdelay: 3
broadcast:
  join: true
ffaworld: world
spawns:
  '1':
    x: 1
    y: 4
    z: 1
    yaw: 1
effect:
  joinblind: true
  joinsound: true
  killsound: true
scoreboard:
  title: '&c&lF&7&lF&c&lA'
region:
  world: world
  p1:
    x: 741.0
    y: 3.0
    z: 503.0
  p2:
    x: 741.0
    y: 3.0
    z: 503.0