name: FFA
version: 9.0-SNAPSHOT
description: Minecraft pvp freeforall minigame!
main: com.harry5573.ffa.Main
softdepend: [Vault, Essentials, mcMMO]
commands:
  ffa: 
    description: Teleport to FFA
    aliases: [freeforall]