name: FFA
version: 10.0-SNAPSHOT
description: Minecraft pvp freeforall minigame!
main: com.harry5573.ffa.FreeForAll
softdepend: [Vault]
commands:
  ffa: 
    description: Teleport to FFA
    aliases: [freeforall]